/**
 * Raw runtime env boundary.
 *
 * Keep direct process.env reads here so the public env facade can stay small
 * and application code keeps importing from "@/lib/env".
 */

export const runtimeEnv = {
  // Server
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  EMAIL_FROM: process.env.EMAIL_FROM,
  EMAIL_REPLY_TO: process.env.EMAIL_REPLY_TO,
  AIRTABLE_API_KEY: process.env.AIRTABLE_API_KEY,
  AIRTABLE_BASE_ID: process.env.AIRTABLE_BASE_ID,
  AIRTABLE_TABLE_NAME: process.env.AIRTABLE_TABLE_NAME,
  TURNSTILE_SECRET_KEY: process.env.TURNSTILE_SECRET_KEY,
  TURNSTILE_ALLOWED_HOSTS: process.env.TURNSTILE_ALLOWED_HOSTS,
  TURNSTILE_ALLOWED_ACTIONS: process.env.TURNSTILE_ALLOWED_ACTIONS,
  TURNSTILE_EXPECTED_ACTION: process.env.TURNSTILE_EXPECTED_ACTION,
  TURNSTILE_BYPASS: process.env.TURNSTILE_BYPASS,
  NEXT_SERVER_ACTIONS_ENCRYPTION_KEY:
    process.env.NEXT_SERVER_ACTIONS_ENCRYPTION_KEY,
  CLOUDFLARE_ZONE_ID: process.env.CLOUDFLARE_ZONE_ID,
  CLOUDFLARE_ACCOUNT_ID: process.env.CLOUDFLARE_ACCOUNT_ID,
  CLOUDFLARE_ANALYTICS_API_TOKEN: process.env.CLOUDFLARE_ANALYTICS_API_TOKEN,
  CLOUDFLARE_ANALYTICS_HOSTNAME: process.env.CLOUDFLARE_ANALYTICS_HOSTNAME,
  OPS_DASHBOARD_ACCESS_KEY: process.env.OPS_DASHBOARD_ACCESS_KEY,
  LOG_LEVEL: process.env.LOG_LEVEL,
  CONTENT_ENABLE_DRAFTS: process.env.CONTENT_ENABLE_DRAFTS,
  DEPLOYMENT_PLATFORM: process.env.DEPLOYMENT_PLATFORM,
  VERCEL: process.env.VERCEL,
  CF_PAGES: process.env.CF_PAGES,
  GOOGLE_SITE_VERIFICATION: process.env.GOOGLE_SITE_VERIFICATION,
  YANDEX_VERIFICATION: process.env.YANDEX_VERIFICATION,
  RATE_LIMIT_PEPPER: process.env.RATE_LIMIT_PEPPER,
  RATE_LIMIT_PEPPER_PREVIOUS: process.env.RATE_LIMIT_PEPPER_PREVIOUS,
  UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
  UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
  KV_REST_API_URL: process.env.KV_REST_API_URL,
  KV_REST_API_TOKEN: process.env.KV_REST_API_TOKEN,
  ALLOW_MEMORY_RATE_LIMIT: process.env.ALLOW_MEMORY_RATE_LIMIT,
  ALLOW_MEMORY_IDEMPOTENCY: process.env.ALLOW_MEMORY_IDEMPOTENCY,
  VERCEL_URL: process.env.VERCEL_URL,
  VERCEL_GIT_COMMIT_SHA: process.env.VERCEL_GIT_COMMIT_SHA,
  VERCEL_ENV: process.env.VERCEL_ENV,
  NODE_ENV: process.env.NODE_ENV,
  APP_ENV: process.env.APP_ENV,
  NEXT_PHASE: process.env.NEXT_PHASE,
  CI: process.env.CI,
  GITHUB_TOKEN: process.env.GITHUB_TOKEN,
  PLAYWRIGHT_TEST: process.env.PLAYWRIGHT_TEST,
  SKIP_ENV_VALIDATION: process.env.SKIP_ENV_VALIDATION,
  SECURITY_HEADERS_ENABLED: process.env.SECURITY_HEADERS_ENABLED,
  CSP_REPORT_URI: process.env.CSP_REPORT_URI,
  CORS_ALLOWED_ORIGINS: process.env.CORS_ALLOWED_ORIGINS,

  // Client
  NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  NEXT_PUBLIC_WEBSITE_BASE_URL: process.env.NEXT_PUBLIC_WEBSITE_BASE_URL,
  NEXT_PUBLIC_WEBSITE_SECONDARY_BASE_URL:
    process.env.NEXT_PUBLIC_WEBSITE_SECONDARY_BASE_URL,
  NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  NEXT_PUBLIC_APP_VERSION: process.env.NEXT_PUBLIC_APP_VERSION,
  NEXT_PUBLIC_SITE_KEY: process.env.NEXT_PUBLIC_SITE_KEY,
  NEXT_PUBLIC_VERCEL_ANALYTICS_ID: process.env.NEXT_PUBLIC_VERCEL_ANALYTICS_ID,
  NEXT_PUBLIC_GA_MEASUREMENT_ID: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID,
  NEXT_PUBLIC_ENABLE_ANALYTICS_PRECONNECT:
    process.env.NEXT_PUBLIC_ENABLE_ANALYTICS_PRECONNECT,
  NEXT_PUBLIC_TURNSTILE_SITE_KEY: process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY,
  NEXT_PUBLIC_TURNSTILE_ACTION: process.env.NEXT_PUBLIC_TURNSTILE_ACTION,
  NEXT_PUBLIC_TURNSTILE_BYPASS: process.env.NEXT_PUBLIC_TURNSTILE_BYPASS,
  NEXT_PUBLIC_ENABLE_ANALYTICS: process.env.NEXT_PUBLIC_ENABLE_ANALYTICS,
  NEXT_PUBLIC_ENABLE_ERROR_REPORTING:
    process.env.NEXT_PUBLIC_ENABLE_ERROR_REPORTING,
  NEXT_PUBLIC_ENABLE_PERFORMANCE_MONITORING:
    process.env.NEXT_PUBLIC_ENABLE_PERFORMANCE_MONITORING,
  NEXT_PUBLIC_DISABLE_REACT_SCAN: process.env.NEXT_PUBLIC_DISABLE_REACT_SCAN,
  NEXT_PUBLIC_DISABLE_DEV_TOOLS: process.env.NEXT_PUBLIC_DISABLE_DEV_TOOLS,
  NEXT_PUBLIC_TEST_MODE: process.env.NEXT_PUBLIC_TEST_MODE,
  NEXT_PUBLIC_DEFAULT_LOCALE: process.env.NEXT_PUBLIC_DEFAULT_LOCALE,
  NEXT_PUBLIC_SUPPORTED_LOCALES: process.env.NEXT_PUBLIC_SUPPORTED_LOCALES,
  NEXT_PUBLIC_ENABLE_CN_FONT_SUBSET:
    process.env.NEXT_PUBLIC_ENABLE_CN_FONT_SUBSET,
  NEXT_PUBLIC_SECURITY_MODE: process.env.NEXT_PUBLIC_SECURITY_MODE,
  NEXT_PUBLIC_NAV_VARIANT: process.env.NEXT_PUBLIC_NAV_VARIANT,
  NEXT_PUBLIC_CONTACT_FORM_COOLDOWN_MS:
    process.env.NEXT_PUBLIC_CONTACT_FORM_COOLDOWN_MS,
  NEXT_PUBLIC_DEPLOYMENT_PLATFORM: process.env.NEXT_PUBLIC_DEPLOYMENT_PLATFORM,
};

export function readRawEnvValue(key: string): string | undefined {
  if (typeof process === "undefined") {
    return undefined;
  }

  return process.env[key];
}

export function shouldSkipEnvValidation(): boolean {
  return readRawEnvValue("SKIP_ENV_VALIDATION") === "true";
}
