/**
 * Raw runtime env boundary.
 *
 * Keep direct process.env reads here so the public env facade can stay small
 * and application code keeps importing from "@/lib/env".
 */

export const runtimeEnv = {
  // Server
  DATABASE_URL: process.env.DATABASE_URL,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  EMAIL_FROM: process.env.EMAIL_FROM,
  EMAIL_REPLY_TO: process.env.EMAIL_REPLY_TO,
  AIRTABLE_API_KEY: process.env.AIRTABLE_API_KEY,
  AIRTABLE_BASE_ID: process.env.AIRTABLE_BASE_ID,
  AIRTABLE_TABLE_NAME: process.env.AIRTABLE_TABLE_NAME,
  TURNSTILE_SECRET_KEY: process.env.TURNSTILE_SECRET_KEY,
  TURNSTILE_ALLOWED_HOSTS: process.env.TURNSTILE_ALLOWED_HOSTS,
  TURNSTILE_ALLOWED_ACTIONS: process.env.TURNSTILE_ALLOWED_ACTIONS,
  TURNSTILE_EXPECTED_ACTION: process.env.TURNSTILE_EXPECTED_ACTION,
  TURNSTILE_BYPASS: process.env.TURNSTILE_BYPASS,
  ADMIN_API_TOKEN: process.env.ADMIN_API_TOKEN,
  CACHE_INVALIDATION_SECRET: process.env.CACHE_INVALIDATION_SECRET,
  NEXT_SERVER_ACTIONS_ENCRYPTION_KEY:
    process.env.NEXT_SERVER_ACTIONS_ENCRYPTION_KEY,
  LOG_LEVEL: process.env.LOG_LEVEL,
  CONTENT_ENABLE_DRAFTS: process.env.CONTENT_ENABLE_DRAFTS,
  DEPLOYMENT_PLATFORM: process.env.DEPLOYMENT_PLATFORM,
  VERCEL: process.env.VERCEL,
  CF_PAGES: process.env.CF_PAGES,
  GOOGLE_SITE_VERIFICATION: process.env.GOOGLE_SITE_VERIFICATION,
  YANDEX_VERIFICATION: process.env.YANDEX_VERIFICATION,
  RATE_LIMIT_PEPPER: process.env.RATE_LIMIT_PEPPER,
  RATE_LIMIT_PEPPER_PREVIOUS: process.env.RATE_LIMIT_PEPPER_PREVIOUS,
  UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
  UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
  KV_REST_API_URL: process.env.KV_REST_API_URL,
  KV_REST_API_TOKEN: process.env.KV_REST_API_TOKEN,
  ALLOW_MEMORY_RATE_LIMIT: process.env.ALLOW_MEMORY_RATE_LIMIT,
  ALLOW_MEMORY_IDEMPOTENCY: process.env.ALLOW_MEMORY_IDEMPOTENCY,
  LINGO_DEV_API_KEY: process.env.LINGO_DEV_API_KEY,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  GROQ_API_KEY: process.env.GROQ_API_KEY,
  GOOGLE_API_KEY: process.env.GOOGLE_API_KEY,
  MISTRAL_API_KEY: process.env.MISTRAL_API_KEY,
  VERCEL_URL: process.env.VERCEL_URL,
  VERCEL_GIT_COMMIT_SHA: process.env.VERCEL_GIT_COMMIT_SHA,
  VERCEL_ENV: process.env.VERCEL_ENV,
  NODE_ENV: process.env.NODE_ENV,
  APP_ENV: process.env.APP_ENV,
  NEXT_PHASE: process.env.NEXT_PHASE,
  CI: process.env.CI,
  GITHUB_TOKEN: process.env.GITHUB_TOKEN,
  PLAYWRIGHT_TEST: process.env.PLAYWRIGHT_TEST,
  SKIP_ENV_VALIDATION: process.env.SKIP_ENV_VALIDATION,
  SECURITY_HEADERS_ENABLED: process.env.SECURITY_HEADERS_ENABLED,
  CSP_REPORT_URI: process.env.CSP_REPORT_URI,
  CORS_ALLOWED_ORIGINS: process.env.CORS_ALLOWED_ORIGINS,

  // Network & API Configuration
  API_TIMEOUT: process.env.API_TIMEOUT,
  UPLOAD_TIMEOUT: process.env.UPLOAD_TIMEOUT,
  WEBSOCKET_TIMEOUT: process.env.WEBSOCKET_TIMEOUT,
  HEALTH_CHECK_TIMEOUT: process.env.HEALTH_CHECK_TIMEOUT,

  // Retry Configuration
  DEFAULT_RETRIES: process.env.DEFAULT_RETRIES,
  API_RETRIES: process.env.API_RETRIES,
  UPLOAD_RETRIES: process.env.UPLOAD_RETRIES,
  RETRY_DELAY_BASE: process.env.RETRY_DELAY_BASE,

  // Rate Limiting
  API_REQUESTS_PER_MINUTE: process.env.API_REQUESTS_PER_MINUTE,
  UPLOADS_PER_HOUR: process.env.UPLOADS_PER_HOUR,
  CONTACT_FORMS_PER_HOUR: process.env.CONTACT_FORMS_PER_HOUR,

  // Development Server Ports
  PORT: process.env.PORT,
  API_PORT: process.env.API_PORT,
  DEV_TOOLS_PORT: process.env.DEV_TOOLS_PORT,
  TEST_PORT: process.env.TEST_PORT,
  MONITORING_PORT: process.env.MONITORING_PORT,
  API_MONITORING_PORT: process.env.API_MONITORING_PORT,

  // Development Experience
  HOT_RELOAD_DELAY: process.env.HOT_RELOAD_DELAY,
  FILE_WATCH_DEBOUNCE: process.env.FILE_WATCH_DEBOUNCE,
  DEV_TOOLS_REFRESH_INTERVAL: process.env.DEV_TOOLS_REFRESH_INTERVAL,

  // Cache Configuration
  STATIC_CACHE_TTL: process.env.STATIC_CACHE_TTL,
  API_CACHE_TTL: process.env.API_CACHE_TTL,
  SESSION_CACHE_TTL: process.env.SESSION_CACHE_TTL,
  I18N_CACHE_TTL: process.env.I18N_CACHE_TTL,

  // Memory Limits
  MAX_UPLOAD_SIZE: process.env.MAX_UPLOAD_SIZE,
  MAX_REQUEST_SIZE: process.env.MAX_REQUEST_SIZE,
  MAX_CACHE_SIZE: process.env.MAX_CACHE_SIZE,
  MAX_LOG_SIZE: process.env.MAX_LOG_SIZE,

  // Performance Monitoring
  PERFORMANCE_SAMPLE_RATE: process.env.PERFORMANCE_SAMPLE_RATE,
  ERROR_SAMPLE_RATE: process.env.ERROR_SAMPLE_RATE,
  MONITORING_INTERVAL: process.env.MONITORING_INTERVAL,
  HEALTH_CHECK_INTERVAL: process.env.HEALTH_CHECK_INTERVAL,

  // Web Vitals Thresholds
  LCP_GOOD_THRESHOLD: process.env.LCP_GOOD_THRESHOLD,
  FID_GOOD_THRESHOLD: process.env.FID_GOOD_THRESHOLD,
  CLS_GOOD_THRESHOLD: process.env.CLS_GOOD_THRESHOLD,
  TTFB_GOOD_THRESHOLD: process.env.TTFB_GOOD_THRESHOLD,

  // Security Configuration
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
  BCRYPT_ROUNDS: process.env.BCRYPT_ROUNDS,
  CSRF_TOKEN_LENGTH: process.env.CSRF_TOKEN_LENGTH,
  SESSION_TIMEOUT: process.env.SESSION_TIMEOUT,

  // Feature Flags
  ENABLE_PERFORMANCE_MONITORING: process.env.ENABLE_PERFORMANCE_MONITORING,
  ENABLE_ERROR_TRACKING: process.env.ENABLE_ERROR_TRACKING,
  ENABLE_AB_TESTING: process.env.ENABLE_AB_TESTING,

  // Client
  NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  NEXT_PUBLIC_WEBSITE_BASE_URL: process.env.NEXT_PUBLIC_WEBSITE_BASE_URL,
  NEXT_PUBLIC_WEBSITE_SECONDARY_BASE_URL:
    process.env.NEXT_PUBLIC_WEBSITE_SECONDARY_BASE_URL,
  NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  NEXT_PUBLIC_APP_VERSION: process.env.NEXT_PUBLIC_APP_VERSION,
  NEXT_PUBLIC_SITE_KEY: process.env.NEXT_PUBLIC_SITE_KEY,
  NEXT_PUBLIC_VERCEL_ANALYTICS_ID: process.env.NEXT_PUBLIC_VERCEL_ANALYTICS_ID,
  NEXT_PUBLIC_GA_MEASUREMENT_ID: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID,
  NEXT_PUBLIC_ENABLE_ANALYTICS_PRECONNECT:
    process.env.NEXT_PUBLIC_ENABLE_ANALYTICS_PRECONNECT,
  NEXT_PUBLIC_TURNSTILE_SITE_KEY: process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY,
  NEXT_PUBLIC_TURNSTILE_ACTION: process.env.NEXT_PUBLIC_TURNSTILE_ACTION,
  NEXT_PUBLIC_TURNSTILE_BYPASS: process.env.NEXT_PUBLIC_TURNSTILE_BYPASS,
  NEXT_PUBLIC_ENABLE_ANALYTICS: process.env.NEXT_PUBLIC_ENABLE_ANALYTICS,
  NEXT_PUBLIC_ENABLE_ERROR_REPORTING:
    process.env.NEXT_PUBLIC_ENABLE_ERROR_REPORTING,
  NEXT_PUBLIC_ENABLE_PERFORMANCE_MONITORING:
    process.env.NEXT_PUBLIC_ENABLE_PERFORMANCE_MONITORING,
  NEXT_PUBLIC_DISABLE_REACT_SCAN: process.env.NEXT_PUBLIC_DISABLE_REACT_SCAN,
  NEXT_PUBLIC_DISABLE_DEV_TOOLS: process.env.NEXT_PUBLIC_DISABLE_DEV_TOOLS,
  NEXT_PUBLIC_TEST_MODE: process.env.NEXT_PUBLIC_TEST_MODE,
  NEXT_PUBLIC_DEFAULT_LOCALE: process.env.NEXT_PUBLIC_DEFAULT_LOCALE,
  NEXT_PUBLIC_SUPPORTED_LOCALES: process.env.NEXT_PUBLIC_SUPPORTED_LOCALES,
  NEXT_PUBLIC_ENABLE_CN_FONT_SUBSET:
    process.env.NEXT_PUBLIC_ENABLE_CN_FONT_SUBSET,
  NEXT_PUBLIC_SECURITY_MODE: process.env.NEXT_PUBLIC_SECURITY_MODE,
  NEXT_PUBLIC_NAV_VARIANT: process.env.NEXT_PUBLIC_NAV_VARIANT,
  NEXT_PUBLIC_CONTACT_FORM_COOLDOWN_MS:
    process.env.NEXT_PUBLIC_CONTACT_FORM_COOLDOWN_MS,
  NEXT_PUBLIC_DEPLOYMENT_PLATFORM: process.env.NEXT_PUBLIC_DEPLOYMENT_PLATFORM,
};

export function readRawEnvValue(key: string): string | undefined {
  if (typeof process === "undefined") {
    return undefined;
  }

  return process.env[key];
}

export function shouldSkipEnvValidation(): boolean {
  return readRawEnvValue("SKIP_ENV_VALIDATION") === "true";
}
